[package]
name = "boids"
version = "0.1.0"
edition = "2021"
description = "A boids simulation in Rust and WebAssembly"
repository = "https://github.com/Blackgaurd/boids"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"

[profile.release]
lto = true
